package com.hazendaz.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1 2013-09-16T20:31:46.893-04:00 Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.hazendaz.com/", name = "HelloWorld")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.hazendaz.com/HelloWorld/getHelloWorldRequest", output = "http://ws.hazendaz.com/HelloWorld/getHelloWorldResponse")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://ws.hazendaz.com/", className = "com.hazendaz.ws.GetHelloWorld")
    @WebMethod
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://ws.hazendaz.com/", className = "com.hazendaz.ws.GetHelloWorldResponse")
    public java.lang.String getHelloWorld(@WebParam(name = "arg0", targetNamespace = "") final java.lang.String arg0);
}
