/*
 * fileUploadResources (https://github.com/hazendaz/fileUploadResources)
 *
 * Copyright 2013-2014 Hazendaz.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of The Apache Software License,
 * Version 2.0 which accompanies this distribution, and is available at
 * https://www.apache.org/licenses/LICENSE-2.0.txt
 *
 * Contributors:
 *     Hazendaz (Jeremy Landis).
 */
package com.hazendaz.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.5.1 2013-09-16T20:31:46.893-04:00 Generated source version: 2.5.1
 * 
 */
public final class HelloWorld_HelloWorldImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.hazendaz.com/", "HelloWorldImplService");

    public static void main(final String[] args) throws Exception {
        URL wsdlURL = HelloWorldImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            final File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (final MalformedURLException e) {
                e.printStackTrace();
            }
        }

        final HelloWorldImplService ss = new HelloWorldImplService(wsdlURL,
                HelloWorld_HelloWorldImplPort_Client.SERVICE_NAME);
        final HelloWorld port = ss.getHelloWorldImplPort();

        {
            System.out.println("Invoking getHelloWorld...");
            final java.lang.String _getHelloWorld_arg0 = "";
            final java.lang.String _getHelloWorld__return = port.getHelloWorld(_getHelloWorld_arg0);
            System.out.println("getHelloWorld.result=" + _getHelloWorld__return);

        }

        System.exit(0);
    }

    private HelloWorld_HelloWorldImplPort_Client() {
    }

}
